-- 도메인 무결성 예시
-- 숫자가 0~~9의 숫자만 입력되도록 설정
CREATE DOMAIN PHONEINT AS INTEGER CHECK (VALUE > 0 AND VALUE < 9);

-- 테이블 생성
CREATE TABLE DOMAIN_TYPE_STUDY(
	ID PHONEINT
)
;

INSERT INTO DOMAIN_TYPE_STUDY VALUES(1); -- 성공
INSERT INTO DOMAIN_TYPE_STUDY VALUES(10); -- 실패

-- 5가지 제약 조건
-- NOT NULL
DROP TABLE IF EXISTS CONTACT_INFO;
CREATE TABLE CONTACT_INFO(
	CONT_ID NUMERIC(3)	NOT NULL,
	NAME	VARCHAR(15)	NOT NULL,
	TEL		INTEGER[]	NOT NULL,
	EMAIL	VARCHAR
)
;

-- NOT NULL & UNIQUE
DROP TABLE IF EXISTS CONTACT_INFO;
CREATE TABLE CONTACT_INFO(
	CONT_ID NUMERIC(3)	UNIQUE NOT NULL,
	NAME	VARCHAR(15)	NOT NULL,
	TEL		INTEGER[]	NOT NULL,
	EMAIL	VARCHAR
)
;

-- 여러 칼럼에 UNIQUE 적용
DROP TABLE IF EXISTS CONTACT_INFO;
CREATE TABLE CONTACT_INFO(
	CONT_ID NUMERIC(3)	NOT NULL,
	NAME	VARCHAR(15)	NOT NULL,
	TEL		INTEGER[]	NOT NULL,
	EMAIL	VARCHAR
	UNIQUE(CONT_ID, TEL, EMAIL)
)
;

-- 기본키 지정
DROP TABLE IF EXISTS CONTACT_INFO;
CREATE TABLE CONTACT_INFO(
	CONT_ID SERIAL		NOT NULL PRIMARY KEY,
	NAME	VARCHAR(15)	NOT NULL,
	TEL		INTEGER[]	NOT NULL,
	EMAIL	VARCHAR
)
;

-- 외래키 지정
CREATE TABLE BOOK(
	BOOK_ID		SERIAL		NOT NULL,
	NAME		VARCHAR(15)	NOT NULL,
	ADMIN_NO	SERIAL		NOT NULL REFERENCES CONTACT_INFO(CONT_ID)
	EMAIL		VARCHAR,
	PRIMARY KEY(BOOK_ID, ADMIN_NO)
); -- 참조 테이블을 하나 만들었다고 생각하면 된다.


-- 예시를 통해 다시 알아보자
-- 학교 / 수업, 선생님

CREATE TABLE SUBJECT(
	SUBJ_ID		NUMERIC(5)		NOT NULL PRIMARY KEY,
	SUBJ_NAME	VARCHAR(10)		NOT NULL
);

INSERT INTO SUBJECT VALUES(00001, '수학'),(00002,'과학'),(00003,'사회');
INSERT INTO SUBJECT VALUES(00004, '국어');

SELECT * FROM SUBJECT

CREATE TABLE TEACHER(
	TEAC_ID				NUMERIC(5)		NOT NULL PRIMARY KEY,
	TEAC_NAME			VARCHAR(20)		NOT NULL,
	SUBJ_ID				NUMERIC(5)		REFERENCES SUBJECT,
	TEACH_CERTIFI_DATE	DATE
);

SELECT * FROM SUBJECT;

INSERT INTO TEACHER VALUES(00001,'정선생',00001,'2023-10-12');
INSERT INTO TEACHER VALUES(00021,'김선생',00002,'2023-10-12');
INSERT INTO TEACHER VALUES(00031,'박선생',00003,'2023-10-12');
INSERT INTO TEACHER VALUES(00041,'이선생',00004,'2023-10-12');
SELECT * FROM TEACHER;
