-- P.115
-- 국가별 TOP PRODUCT 및 매출
-- 미국의 연도별 TOP5 차량 모델 추출 (매출액 기준)
-- 사용 테이블 : ORDER 테이블, ORDERDETAILS 테이블, CUSTOMERS 테이블
-- + PRODUCTS 테이블

USE CLASSICMODELS;

SELECT
	QUANTITYORDERED
    , PRICEEACH
FROM ORDERS A 
LEFT
JOIN ORDERDETAILS B
ON A.ORDERNUMBER = B.ORDERNUMBER
;

CREATE TABLE CLASSICMODELS.PRODUCT_SALE AS
SELECT
	D.PRODUCTNAME
    , SUM(QUANTITYORDERED*PRICEEACH) AS SALES
FROM ORDERS A
LEFT
JOIN CUSTOMERS B
ON A.CUSTOMERNUMBER = B.CUSTOMERNUMBER
LEFT
JOIN ORDERDETAILS C
ON A.ORDERNUMBER = C.ORDERNUMBER
LEFT
JOIN PRODUCTS D
ON C.PRODUCTCODE = D.PRODUCTCODE
WHERE B.COUNTRY = 'USA'
GROUP BY 1
;

SELECT * FROM PRODUCT_SALE;

SELECT *
FROM(
	SELECT *
    , ROW_NUMBER() OVER(ORDER BY SALES DESC) RNK
    FROM PRODUCT_SALE) A
WHERE RNK <=5
ORDER BY RNK;

-- [CHURN RATE (%)]
-- 이탈 고객
-- CHURN : MAX(구매일, 접속일) 이후 일정 기간 (EX. 3개월)
-- 보통은 GOOGLE ANALITI.. 툴을 이용해 많이 사용한다.
-- 구매, 접속하지 않은 상태

SELECT
	CUSTOMERNUMBER
	, MIN(ORDERDATE) '최초 구매일'
	, MAX(ORDERDATE) '마지막 구매일'
FROM ORDERS
GROUP BY 1;

-- 2005-06-01일 기준으로 각 고객의 마지막 구매일이 며칠 소요되는가?
-- DATEDIFF 사용 (DATE1, DATE2)
SELECT DATEDIFF('2004-11-05', '2004-11-01');

-- 전체 코드 확인
SELECT
	CUSTOMERNUMBER
    , MAX(ORDERDATE) MX_ORDER -- 이 테이블의 마지막 구매일 (전 고객 기준)
    -- GROUP BY 마지막 구매일 (각 고객 기준)
FROM ORDERS
GROUP BY 1;

SELECT
	CUSTOMERNUMBER
    , MX_ORDER
    , '2005-06-01' -- 전 고객 대상 마지막 구매일
    , DATEDIFF('2005-06-01', MX_ORDER) DIFF
FROM (
SELECT
	CUSTOMERNUMBER
    , MAX(ORDERDATE) MX_ORDER
FROM ORDERS
GROUP BY 1
) BASE
;

-- P.119
-- 조건 DIFF가 90일 이상이면 CHURN이라고 가정한다. CHURN 또는 NON CHURN
-- IF 조건문, SQL 쿼리상에선 CASE WHEN
-- 메인퀘리 : 90일 이상이면 CHURN이라고 가정한다. CHURN 또는 NON CHURN
-- 서브쿼리 : DIFF를 구하는 것이 서브쿼리

  
SELECT
	*
  , CASE WHEN DIFF >= 90 THEN 'CHURN' ELSE 'NON CHURN' END AS CustomerStatus
FROM (
  SELECT   
    CUSTOMERNUMBER
    , MX_ORDER
    , '2005-06-01'
    , DATEDIFF('2005-06-01', MX_ORDER) AS DIFF 
  FROM (
    SELECT    
      CUSTOMERNUMBER
      , MAX(ORDERDATE) AS MX_ORDER
    FROM ORDERS   
    GROUP BY CUSTOMERNUMBER
  ) AS BASE1     
) AS BASE2
;

-- 매출액 기준) 차량모델을 찾는 것이 핵심코드
-- ERD 기준, CUSTOMERS PRODUCTS
-- 1차 제외 : 주문안한 고객
-- 2차 제외 : 차량모델 코드 중 주문이 없는 차량모델 제외
-- 3차 제외 : USA 제외 CUSTOMER 테이블 참조

SELECT
  CASE WHEN DIFF >= 90 THEN 'CHURN' ELSE 'NON CHURN' END AS CustomerStatus
  , COUNT(*) AS TotalCount
FROM (
  SELECT   
    CUSTOMERNUMBER
    , MX_ORDER
    , '2005-06-01'
    , DATEDIFF('2005-06-01', MX_ORDER) AS DIFF 
  FROM (
    SELECT    
      CUSTOMERNUMBER
      , MAX(ORDERDATE) AS MX_ORDER
    FROM ORDERS   
    GROUP BY CUSTOMERNUMBER
  ) AS BASE1     
) AS BASE2
GROUP BY 1
;

-- CHURN 고객이 가장 많이 구매한 PRODUCTLINE

CREATE TABLE churn_list AS 
SELECT 
	CASE WHEN DIFF >= 90 THEN 'CHURN ' ELSE 'NON-CHURN' END CHURN_TYPE
    , customernumber
FROM 
	(
		SELECT 
			customernumber
			, mx_order
			, '2005-06-01' END_POINT
			, DATEDIFF('2005-06-01', mx_order) DIFF
		FROM
			(
				SELECT 
					customernumber
					, max(orderdate) mx_order
				FROM orders
				GROUP BY 1
			) BASE
    ) BASE
;

SELECT * FROM CHURN_LIST;

-- CHURN 고객은 어떤 카테고리의 상품을 많이 구매했는가?
SELECT * FROM PRODUCTLINES;

-- P.122
SELECT
	C.PRODUCTLINE
    , COUNT(DISTINCT B.CUSTOMERNUMBER) BU
FROM ORDERDETAILS A
LEFT
JOIN ORDERS B
ON A.ORDERNUMBER = B.ORDERNUMBER
LEFT
JOIN PRODUCTS C
ON A.PRODUCTCODE = C.PRODUCTCODE
GROUP BY 1
;

-- CHURN TYPE, PRODUCT LINE 별 구매자수
SELECT
	D.CHURN_TYPE
	, C.PRODUCTLINE
    , COUNT(DISTINCT B.CUSTOMERNUMBER) BU
FROM ORDERDETAILS A
LEFT
JOIN ORDERS B
ON A.ORDERNUMBER = B.ORDERNUMBER
LEFT
JOIN PRODUCTS C
ON A.PRODUCTCODE = C.PRODUCTCODE
LEFT
JOIN CHURN_LIST D
ON B.CUSTOMERNUMBER = D.CUSTOMERNUMBER
GROUP BY 1, 2
ORDER BY 1, 3 DESC
;
        