USE MYDATA;
-- P.206
-- RFM : 가치있는 고객을 추출하는 방법론, 고객 세그먼트
-- P.207

-- 게임사 확인
-- R : 제일 최근에 구입한 시기
-- F : 어느 정도로 자주 구입했는가?
-- MONETARY : 구입한 총 금액은 얼마인가?

-- RECENCY : 계산해보자, 거래의 최근성을 나타내는 지표
SELECT
	CUSTOMERID
    , MAX(INVOICEDATE) MXDT
FROM DATASET3
GROUP BY 1
;

SELECT
	CUSTOMERID
    , DATEDIFF('2011-12-02', MXDT) RECENCY
FROM(
SELECT
	CUSTOMERID
    , MAX(INVOICEDATE) MXDT
FROM DATASET3
GROUP BY 1
) A
;

SELECT
	CUSTOMERID
    , COUNT(DISTINCT INVOICENO) FREQUENCY
    , SUM(QUANTITY*UNITPRICE) MONETARY
FROM DATASET3
GROUP BY 1
;

SELECT 
	customerid
    , datediff('2011-12-02', mxdt) RECENCY 
    , frequency
    , monetary
FROM (
	SELECT 
		customerid
		, MAX(invoiceDate) MXDT 
		, COUNT(DISTINCT invoiceno) AS frequency
		, SUM(quantity * unitprice) AS monetary 
	FROM dataset3
	GROUP BY 1
) A
;

-- 고객별, 상품별 구매연도를 UNIQUE하게 CNT
SELECT
	CUSTOMERID
    , STOCKCODE
    , COUNT(DISTINCT SUBSTR(INVOICEDATE, 1, 4)) UNIQUE_YY
FROM DATASET3
GROUP BY 1,2
;

-- UNIQUE_YY 가 2 이상인 고객과 그렇지 않은 고객을 구분한다.
SELECT
	CUSTOMERID
    , MAX(UNIQUE_YY) MX_UNIQUE_YY
FROM(
SELECT
	CUSTOMERID
    , STOCKCODE
    , COUNT(DISTINCT SUBSTR(INVOICEDATE, 1, 4)) UNIQUE_YY
FROM DATASET3
GROUP BY 1,2
) A
GROUP BY 1
;

-- 문제 MX_UNIQUE_YY 2이상이면 1, 그 외에는 0
-- CASE WHEN 사용해서 처리

SELECT 
	CUSTOMERID
	, CASE WHEN `MX_UNIQUE_YY` >= 2 THEN 1 ELSE 0 END REPURCHASE_SEGMENT
FROM(
SELECT
	CUSTOMERID
    , MAX(UNIQUE_YY) MX_UNIQUE_YY
FROM(
SELECT
	CUSTOMERID
    , STOCKCODE
    , COUNT(DISTINCT SUBSTR(INVOICEDATE, 1, 4)) UNIQUE_YY
FROM DATASET3
GROUP BY 1,2
) A
GROUP BY 1
)A
GROUP BY 1
;

SELECT
	CUSTOMERID
    , MIN(INVOICEDATE) MNDT
FROM DATASET3
GROUP BY CUSTOMERID;

-- 일자별로 고객 수를 CNT 일자별 첫 구매 고객 수를 계산할 수 있음
SELECT
	MNDT
    , COUNT(DISTINCT CUSTOMERID) BU
FROM(
SELECT
	CUSTOMERID
    , MIN(INVOICEDATE) MNDT
FROM DATASET3
GROUP BY CUSTOMERID
) A
GROUP BY 1
;

-- 첫 구매 고객 중에서 얼마나 많은 고객이 이탈하는지 계산해보자
-- 첫 구매 고객의 이탈율 계산
-- 고객 별로 구매일자의 중복 제거 CNT

SELECT
    SUM(CASE WHEN F_DATE = 1 THEN 1 ELSE 0 END)/SUM(1) AS BOUNC_RATE
FROM(
SELECT
	CUSTOMERID
    , COUNT(DISTINCT INVOICEDATE) F_DATE
FROM DATASET3
GROUP BY 1
) A
;

SELECT COUNTRY
	, SUM(CASE WHEN F_DATE = 1 THEN 1 ELSE 0 END) / SUM(1) BOUNC_RATE
FROM(
SELECT
	CUSTOMERID
    , COUNTRY
	, COUNT(DISTINCT INVOICEDATE) AS F_DATE
FROM DATASET3
GROUP BY 1,2
) A
GROUP BY 1
ORDER BY 1
;